config/routes.rb
Rails.application.routes.draw do
    get 'code_snippets/index'
    
    get 'index' => "code_snippets#index"
    get 'code_display' => "code_snippets#code_display"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'code_snippets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/code_snippet.rb
class CodeSnippet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/code_snippets_controller.rb
class CodeSnippetsController < ApplicationController
    
    def index
    end
    
    def code_display
        @language = params[:language]
        @declaration_snippets = CodeSnippet.where(language: @language, category: "declaration")
        @condition_snippets = CodeSnippet.where(language: @language, category: "condition")
        @loop_snippets = CodeSnippet.where(language: @language, category: "loop")
        color_display
    end

    def color_display
      case @language
        when "c"
          @color = "#1a8cff"
        when "cpp"
          @color = "#66c2ff"
        when "java"
          @color = "#ffad33"
        when "javascript"
          @color = "#ffff4d"
        when "python"
          @color = "#2eb82e"
        when "ruby"
          @color = "#ff3333"
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/code_snippets_helper.rb
module CodeSnippetsHelper
end

app/views/code_snippets/_structure.html.erb
	<body class="grid">
		<title> Capsule 001 </title>

		<div class="header" style="background-color: <%= @color %>">
			<h1> <%= link_to 'Capsule 001', index_path %> </h1>
    </div>

		<div class="menu">
			<ul>
				<li> <%= link_to 'C', code_display_path(:language => 'c') %> </li>
				<li> <%= link_to 'C++', code_display_path(:language => 'cpp') %> </li>
				<li> <%= link_to 'Java', code_display_path(:language => 'java') %> </li>
				<li> <%= link_to 'JavaScript', code_display_path(:language => 'javascript') %> </li>
				<li> <%= link_to 'Python', code_display_path(:language => 'python') %> </li>
				<li> <%= link_to 'Ruby', code_display_path(:language => 'ruby') %> </li>
			</ul>
		</div>

app/views/code_snippets/code_display.html.erb
<%= render 'structure' %>

<div class="main">
        
    
    <h1> Declarations </h1>
    <div class="content">
    <% @declaration_snippets.each do |snippet| %>
        <figure> <%= snippet.name %>
            <pre><code class = "language-<%= snippet.language %>">

<%= snippet.content %>

            </code></pre>
        </figure>
        <% end %>
    </div>
        
        
        
    <h1> Conditions </h1>
    <div class="content">
    <% @condition_snippets.each do |snippet| %>
        <figure> <%= snippet.name %>
            <pre><code class = "language-<%= snippet.language %>">

<%= snippet.content %>

            </code></pre>
        </figure>
        <% end %>
    </div>
    
        
    <h1> Loops </h1>
    <div class="content">
    <% @loop_snippets.each do |snippet| %>
        <figure> <%= snippet.name %>
            <pre><code class = "language-<%= snippet.language %>">

<%= snippet.content %>

            </code></pre>
        </figure>
        <% end %>
    </div>
            
</div>

app/views/code_snippets/index.html.erb
<%= render 'structure' %>

<div class="main">

  <h1> POOF! </h1>
  <h1> You just launched capsule 001. Congratulations! </h1>
  <h2> Select a language to display its features </h2>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Capsule001</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>